### ISSUE TITLE
Run inference on only CT input

### ISSUE THREAD

**Issue by ding3820** [steve-zeyu-zhang/SegReg#1]
Hi, 

Thanks for sharing the great work! I was wondering if I can run your model on only CT input. I saw you made an ablation study on this and the results were comparable to SepNet. I would like to try it out with my data on hand. Please let me know if there is anything I need to modify in order to make it work! 

Look forward to hearing back from you! Thanks!

**Comment by ding3820** [comment]
and just a reminder that your public docker image has nothing inside, no any implementation in `code` or `workspace` folder.

**Comment by steve-zeyu-zhang** [comment]
> Hi,
> 
> Thanks for sharing the great work! I was wondering if I can run your model on only CT input. I saw you made an ablation study on this and the results were comparable to SepNet. I would like to try it out with my data on hand. Please let me know if there is anything I need to modify in order to make it work!
> 
> Look forward to hearing back from you! Thanks!

Hi @ding3820 ,

Please note that provided docker images are contains any code instead the required torch **environment.**

SegReg is not designed for CT only purpose. It requires multi-modal input to achieve registration segmentation (mainly CT-MRI OAR segmentation now, and we're  working on extending it to other application in [SegReg v2](https://steve-zeyu-zhang.github.io/SegRegv2/), stay tuned). If you want to implement the same CT-only ablation in our paper, please visit the [nnUNet](https://github.com/MIC-DKFZ/nnUNet/tree/nnunetv1) backbone, and let me know if you need our pretrained CT-only checkpoint on [HaN-Seg](https://han-seg2023.grand-challenge.org/) for OAR segmentation, I might able to find it for you.

I'm closing the issue now, feel free to re-open it anytime if there's more question.

Steve

**Comment by steve-zeyu-zhang** [comment]
> Hi,
> 
> Thanks for sharing the great work! I was wondering if I can run your model on only CT input. I saw you made an ablation study on this and the results were comparable to SepNet. I would like to try it out with my data on hand. Please let me know if there is anything I need to modify in order to make it work!
> 
> Look forward to hearing back from you! Thanks!

Hi @ding3820 ,

Please note that provided docker image does not contain any code instead the required torch **environment.**

SegReg is not designed for CT only purpose. It requires multi-modal input to achieve registration segmentation (mainly CT-MRI OAR segmentation now, and we're  working on extending it to other application in [SegReg v2](https://steve-zeyu-zhang.github.io/SegRegv2/), stay tuned). If you want to implement the same CT-only ablation in our paper, please visit the [nnUNet](https://github.com/MIC-DKFZ/nnUNet/tree/nnunetv1) backbone, and let me know if you need our pretrained CT-only checkpoint on [HaN-Seg](https://han-seg2023.grand-challenge.org/) for OAR segmentation, I might able to find it for you.

I'm closing the issue now, feel free to re-open it anytime if there's more question.

Steve
